"""
╔══════════════════════════════════════════════════════════════╗
║           AGENT LOOP — Continuous Observe-Think-Act-Reflect ║
║   The AI's main lifecycle — always running, always learning ║
╚══════════════════════════════════════════════════════════════╝

The Agent Loop is the AI's heartbeat — a continuous cycle that:

    1. OBSERVE — Monitor inputs (user actions, notifications, events)
    2. THINK    — Analyze, decide if action is needed
    3. ACT      — Execute through Cognitive Engine
    4. REFLECT  — Evaluate outcome
    5. LEARN    — Update memories, skills, preferences
    6. IMPROVE  — Optimize for next cycle

This runs continuously in the background, waking periodically
to check for new inputs and proactive opportunities.
"""

import logging
import time
import threading
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Callable
from dataclasses import dataclass, field
from collections import deque

logger = logging.getLogger(__name__)


@dataclass
class Observation:
    """Something observed by the AI that may need processing."""
    obs_type: str           # 'user_input', 'notification', 'screen_change', 'time_event', 'system_event'
    content: str
    source: str = ""        # Which app/module generated this
    timestamp: float = 0.0
    importance: float = 0.5
    processed: bool = False
    metadata: dict = field(default_factory=dict)


@dataclass
class Insight:
    """An insight or suggestion generated by reflection."""
    insight_type: str       # 'suggestion', 'improvement', 'warning', 'insight'
    content: str
    confidence: float = 0.5
    source: str = ""
    timestamp: float = 0.0
    acted_upon: bool = False


@dataclass
class DailySummary:
    """End-of-day summary of activity."""
    date: str
    total_observations: int = 0
    actions_taken: int = 0
    success_rate: float = 1.0
    avg_response_time_ms: float = 0.0
    reflex_ratio: float = 0.0
    top_intents: List[str] = field(default_factory=list)
    insights: List[str] = field(default_factory=list)
    improvements: List[str] = field(default_factory=list)
    learning_highlights: List[str] = field(default_factory=list)


class AgentLoop:
    """The continuous Observe → Think → Act → Reflect → Learn → Improve cycle.

    This is the AI's main lifecycle. It runs as a background daemon,
    waking periodically to check for new observations and proactive
    opportunities.

    The loop is designed to be:
    - Non-blocking (observations are queued, processed asynchronously)
    - Prioritized (high-importance observations processed first)
    - Learning (every cycle improves future cycles)
    """

    def __init__(
        self,
        cognitive_engine=None,
        learning_system=None,
        memory_consolidation=None,
        check_interval: float = 5.0,  # Check every 5 seconds
        proactive_interval: float = 300.0,  # Proactive check every 5 min
        reflection_interval: float = 3600.0,  # Self-reflection every hour
        enable_proactive: bool = True,
    ):
        self.cognitive_engine = cognitive_engine
        self.learning_system = learning_system
        self.memory_consolidation = memory_consolidation

        self.check_interval = check_interval
        self.proactive_interval = proactive_interval
        self.reflection_interval = reflection_interval
        self.enable_proactive = enable_proactive

        # Observation queue
        self._observations: deque = deque(maxlen=200)
        self._lock = threading.RLock()

        # Insights and summaries
        self._insights: List[Insight] = []
        self._daily_summaries: List[DailySummary] = []

        # Timing tracking
        self._last_proactive_check: float = 0.0
        self._last_reflection: float = 0.0
        self._last_daily_summary: str = ""  # Date of last daily summary

        # Runtime state
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._cycle_count = 0
        self._observations_processed = 0
        self._actions_taken = 0

    # ═══════════════════════════════════════════════════════════════
    # LIFECYCLE
    # ═══════════════════════════════════════════════════════════════

    def start(self):
        """Start the agent loop in a background thread."""
        if self._running:
            logger.warning("AgentLoop: Already running")
            return

        self._running = True
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()
        logger.info(f"AgentLoop: Started (cycle={self.check_interval}s, proactive={self.proactive_interval}s)")

    def stop(self):
        """Stop the agent loop."""
        self._running = False
        logger.info("AgentLoop: Stopped")

    def observe(self, obs_type: str, content: str, source: str = "",
                importance: float = 0.5, metadata: Dict = None) -> None:
        """Queue an observation for processing.

        This is the main input method — call this whenever
        something happens that the AI should be aware of.

        Args:
            obs_type: Type of observation ('user_input', 'notification', etc.)
            content: The observation content.
            source: Source of the observation.
            importance: Importance score (0.0-1.0).
            metadata: Additional metadata.
        """
        obs = Observation(
            obs_type=obs_type,
            content=content,
            source=source,
            timestamp=time.time(),
            importance=min(1.0, max(0.0, importance)),
            metadata=metadata or {},
        )

        with self._lock:
            self._observations.append(obs)

        logger.debug(f"AgentLoop: Observed [{obs_type}] '{content[:60]}' (importance={importance})")

    # ═══════════════════════════════════════════════════════════════
    # MAIN LOOP
    # ═══════════════════════════════════════════════════════════════

    def _run(self):
        """The main agent loop."""
        while self._running:
            try:
                self._cycle()

                # Check if we should do proactive work
                now = time.time()
                if self.enable_proactive and (now - self._last_proactive_check) >= self.proactive_interval:
                    self._proactive_check()
                    self._last_proactive_check = now

                # Check if we should do reflection
                if (now - self._last_reflection) >= self.reflection_interval:
                    self._self_reflection()
                    self._last_reflection = now

                # Check if we should generate daily summary
                self._check_daily_summary()

                self._cycle_count += 1
                time.sleep(self.check_interval)

            except Exception as e:
                logger.error(f"AgentLoop: Cycle error: {e}")
                time.sleep(self.check_interval * 2)  # Back off on error

    def _cycle(self):
        """One complete Observe → Think → Act → Reflect → Learn cycle."""
        # ── 1. OBSERVE ──────────────────────────────────────────
        observations = self._get_pending_observations()
        if not observations:
            return

        # Process highest importance first
        observations.sort(key=lambda o: o.importance, reverse=True)

        for obs in observations:
            try:
                # ── 2. THINK ────────────────────────────────────
                # Decide if this needs action
                needs_action = self._should_act(obs)
                if not needs_action:
                    obs.processed = True
                    continue

                # ── 3. ACT ──────────────────────────────────────
                if self.cognitive_engine:
                    result = self.cognitive_engine.process(
                        obs.content,
                        user_id="default",
                        emotion=obs.metadata.get("emotion", "neutral"),
                        topic=obs.metadata.get("topic", obs.obs_type),
                    )
                    self._actions_taken += 1

                    # ── 4. REFLECT ──────────────────────────────
                    self._reflect_on_action(obs, result)

                    # ── 5. LEARN ────────────────────────────────
                    if self.learning_system:
                        learnings = self.learning_system.observe(result)
                        if any(learnings.values()):
                            logger.debug(f"AgentLoop: Learned from action — {learnings}")

                obs.processed = True
                self._observations_processed += 1

            except Exception as e:
                logger.error(f"AgentLoop: Error processing observation: {e}")
                obs.processed = True  # Don't retry failed observations

    def _get_pending_observations(self) -> List[Observation]:
        """Get all unprocessed observations."""
        with self._lock:
            pending = [o for o in self._observations if not o.processed]
            return list(pending)

    def _should_act(self, obs: Observation) -> bool:
        """Decide whether an observation requires action.

        Returns False for:
        - Low importance noise
        - Observations that are just informational
        """
        # Always act on direct user input
        if obs.obs_type == "user_input":
            return True

        # Act on high-importance notifications
        if obs.obs_type == "notification" and obs.importance >= 0.6:
            return True

        # Act on important time events
        if obs.obs_type == "time_event" and obs.importance >= 0.7:
            return True

        # Skip low-importance observations
        if obs.importance < 0.3:
            return False

        return False

    def _reflect_on_action(self, obs: Observation, result):
        """Reflect on an action outcome."""
        if not result:
            return

        if isinstance(result, dict):
            success = result.get('success', True)
            time_ms = result.get('execution_time_ms', 0)
        else:
            success = getattr(result, 'success', True) if hasattr(result, 'success') else True
            time_ms = getattr(result, 'execution_time_ms', 0)

        # Generate insights from failures
        if not success:
            self._insights.append(Insight(
                insight_type="improvement",
                content=f"Failed to process: '{obs.content[:60]}'",
                confidence=0.8,
                source="reflection",
                timestamp=time.time(),
            ))

        # Generate insights from slow actions
        if time_ms > 2000:
            self._insights.append(Insight(
                insight_type="suggestion",
                content=f"Slow processing ({time_ms:.0f}ms) for '{obs.content[:40]}'. Consider optimization.",
                confidence=0.5,
                source="reflection",
                timestamp=time.time(),
            ))

    # ═══════════════════════════════════════════════════════════════
    # PROACTIVE BEHAVIOR
    # ═══════════════════════════════════════════════════════════════

    def _proactive_check(self):
        """Check if the AI should proactively suggest or do something.

        This runs periodically and looks for:
        - Time-based opportunities (morning briefing, evening review)
        - Idle opportunities (user hasn't interacted recently)
        - Habit predictions (user usually does X now)
        """
        if not self.cognitive_engine:
            return

        now = datetime.now()
        hour = now.hour

        try:
            # Check habit brain for predictions
            habit_prediction = getattr(
                self.cognitive_engine.habit, 'predict', None
            )
            if habit_prediction:
                # Create a context to check habits
                from app.and9.brain.cognitive_engine import CognitiveContext
                ctx = CognitiveContext(raw_input="__proactive_check__")
                prediction = habit_prediction(ctx)
                if prediction:
                    logger.info(
                        f"AgentLoop: Proactive — habit predicts '{prediction.get('predicted_action', '?')}' "
                        f"(conf={prediction.get('confidence', 0):.2f})"
                    )

            # Morning/Evening routine checks
            if hour == 7:  # Morning
                logger.info("AgentLoop: Morning — ready for daily briefing")
            elif hour == 21:  # Evening
                logger.info("AgentLoop: Evening — ready for daily review")

        except Exception as e:
            logger.debug(f"AgentLoop: Proactive check error: {e}")

    # ═══════════════════════════════════════════════════════════════
    # SELF-REFLECTION
    # ═══════════════════════════════════════════════════════════════

    def _self_reflection(self):
        """Periodic self-reflection to evaluate performance."""
        if not self.cognitive_engine:
            return

        try:
            reflection = self.cognitive_engine.reflection.get_daily_reflection()
            logger.info(f"AgentLoop: Self-reflection — {reflection.get('summary', '')[:100]}")
            return reflection
        except Exception as e:
            logger.debug(f"AgentLoop: Self-reflection error: {e}")
            return None

    def _check_daily_summary(self):
        """Generate daily summary at end of day."""
        today = datetime.now().strftime("%Y-%m-%d")
        if today == self._last_daily_summary:
            return

        # Only generate at the end of the day (11 PM)
        if datetime.now().hour < 22:
            return

        # Check if we already did today
        if self._last_daily_summary:
            return

        try:
            summary = DailySummary(
                date=today,
                total_observations=self._observations_processed,
                actions_taken=self._actions_taken,
                insights=[i.content for i in self._insights[-5:]],
            )

            if self.cognitive_engine:
                reflection = self.cognitive_engine.get_daily_reflection()
                summary.improvements = reflection.get("suggestions", [])

            self._daily_summaries.append(summary)
            self._last_daily_summary = today

            logger.info(f"AgentLoop: Daily summary for {today} — "
                       f"{summary.total_observations} observations, {summary.actions_taken} actions")

        except Exception as e:
            logger.warning(f"AgentLoop: Daily summary error: {e}")

    # ═══════════════════════════════════════════════════════════════
    # UTILITIES
    # ═══════════════════════════════════════════════════════════════

    def get_pending_observations_count(self) -> int:
        """Get count of unprocessed observations."""
        with self._lock:
            return sum(1 for o in self._observations if not o.processed)

    def get_stats(self) -> dict:
        return {
            "running": self._running,
            "cycle_count": self._cycle_count,
            "observations_processed": self._observations_processed,
            "actions_taken": self._actions_taken,
            "pending_observations": self.get_pending_observations_count(),
            "insights_generated": len(self._insights),
            "daily_summaries": len(self._daily_summaries),
            "uptime_seconds": self._cycle_count * self.check_interval,
        }

    def get_recent_insights(self, limit: int = 10) -> List[Dict]:
        """Get recent insights."""
        return [
            {
                "type": i.insight_type,
                "content": i.content,
                "confidence": round(i.confidence, 2),
                "source": i.source,
                "timestamp": i.timestamp,
                "acted_upon": i.acted_upon,
            }
            for i in self._insights[-limit:]
        ]
